name: bookswap
description: A Flutter app for community resource exchange.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  dio: ^5.7.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  uuid: ^4.5.0
  image_picker: ^1.1.2 # Add this for image picking
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.0.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.12
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_background.jpg  # Changed from .png to .jpg
    - assets/launch.jpg
    - assets/login_background.png
    - assets/background_signup.png
    - assets/profile_background.jpg
    - assets/user1.png